# Generated by Django 5.0.3 on 2024-03-25 01:33

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number', regex='^01[0125]{1}[0-9]{8}$')])),
                ('profile_picture', models.ImageField(blank=True, default='users/images/default_profile_picture.jpg', null=True, upload_to='users/images')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
